#!/bin/bash

VPORT=5000
gst-launch-0.10 -v udpsrc port=$VPORT caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)JPEG, payload=(int)96, ssrc=(uint)3550447310, clock-base=(uint)3425971710, seqnum-base=(uint)9917' ! rtpjpegdepay ! jpegdec ! xvimagesink
